/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as EnRouteImport } from './routes/en'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsIndexRouteImport } from './routes/proposals.index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ProposalsSlugRouteImport } from './routes/proposals.$slug'
import { Route as ModelsR950RouteImport } from './routes/models.r-950'
import { Route as ModelsR680RouteImport } from './routes/models.r-680'
import { Route as ModelsR520RouteImport } from './routes/models.r-520'
import { Route as ModelsSeriesRouteImport } from './routes/models.$series'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnStockRouteImport } from './routes/en.stock'
import { Route as EnProposalsRouteImport } from './routes/en.proposals'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnOffersRouteImport } from './routes/en.offers'
import { Route as EnModelsRouteImport } from './routes/en.models'
import { Route as EnDealersRouteImport } from './routes/en.dealers'
import { Route as EnCookiesRouteImport } from './routes/en.cookies'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnConfiguratorRouteImport } from './routes/en.configurator'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as ModelsSeriesIndexRouteImport } from './routes/models.$series.index'
import { Route as EnProposalsIndexRouteImport } from './routes/en.proposals.index'
import { Route as EnModelsIndexRouteImport } from './routes/en.models.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ModelsSeriesModelRouteImport } from './routes/models.$series.$model'
import { Route as EnProposalsSlugRouteImport } from './routes/en.proposals.$slug'
import { Route as EnModelsSeriesRouteImport } from './routes/en.models.$series'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin.system'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProposalsRouteImport } from './routes/_authenticated/admin.proposals'
import { Route as AuthenticatedAdminModelsRouteImport } from './routes/_authenticated/admin.models'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminDealersRouteImport } from './routes/_authenticated/admin.dealers'
import { Route as AuthenticatedAdminDatabaseRouteImport } from './routes/_authenticated/admin.database'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as EnModelsSeriesIndexRouteImport } from './routes/en.models.$series.index'
import { Route as EnModelsSeriesModelRouteImport } from './routes/en.models.$series.$model'
import { Route as AuthenticatedAdminContentHistoryRouteImport } from './routes/_authenticated/admin.content.history'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProposalsRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const ProposalsSlugRoute = ProposalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProposalsRoute,
} as any)
const ModelsR950Route = ModelsR950RouteImport.update({
  id: '/r-950',
  path: '/r-950',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsR680Route = ModelsR680RouteImport.update({
  id: '/r-680',
  path: '/r-680',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsR520Route = ModelsR520RouteImport.update({
  id: '/r-520',
  path: '/r-520',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsSeriesRoute = ModelsSeriesRouteImport.update({
  id: '/$series',
  path: '/$series',
  getParentRoute: () => ModelsRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const EnStockRoute = EnStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => EnRoute,
} as any)
const EnProposalsRoute = EnProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnOffersRoute = EnOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => EnRoute,
} as any)
const EnModelsRoute = EnModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => EnRoute,
} as any)
const EnDealersRoute = EnDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => EnRoute,
} as any)
const EnCookiesRoute = EnCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnConfiguratorRoute = EnConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const ModelsSeriesIndexRoute = ModelsSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsSeriesRoute,
} as any)
const EnProposalsIndexRoute = EnProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnProposalsRoute,
} as any)
const EnModelsIndexRoute = EnModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnModelsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ModelsSeriesModelRoute = ModelsSeriesModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => ModelsSeriesRoute,
} as any)
const EnProposalsSlugRoute = EnProposalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnProposalsRoute,
} as any)
const EnModelsSeriesRoute = EnModelsSeriesRouteImport.update({
  id: '/$series',
  path: '/$series',
  getParentRoute: () => EnModelsRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/admin/system',
    path: '/admin/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProposalsRoute =
  AuthenticatedAdminProposalsRouteImport.update({
    id: '/admin/proposals',
    path: '/admin/proposals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModelsRoute =
  AuthenticatedAdminModelsRouteImport.update({
    id: '/admin/models',
    path: '/admin/models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDealersRoute =
  AuthenticatedAdminDealersRouteImport.update({
    id: '/admin/dealers',
    path: '/admin/dealers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDatabaseRoute =
  AuthenticatedAdminDatabaseRouteImport.update({
    id: '/admin/database',
    path: '/admin/database',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/admin/content',
    path: '/admin/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EnModelsSeriesIndexRoute = EnModelsSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnModelsSeriesRoute,
} as any)
const EnModelsSeriesModelRoute = EnModelsSeriesModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => EnModelsSeriesRoute,
} as any)
const AuthenticatedAdminContentHistoryRoute =
  AuthenticatedAdminContentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAdminContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dealers': typeof DealersRoute
  '/en': typeof EnRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/terms': typeof TermsRoute
  '/en/about': typeof EnAboutRoute
  '/en/configurator': typeof EnConfiguratorRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/dealers': typeof EnDealersRoute
  '/en/models': typeof EnModelsRouteWithChildren
  '/en/offers': typeof EnOffersRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/proposals': typeof EnProposalsRouteWithChildren
  '/en/stock': typeof EnStockRoute
  '/en/terms': typeof EnTermsRoute
  '/models/$series': typeof ModelsSeriesRouteWithChildren
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
  '/proposals/$slug': typeof ProposalsSlugRoute
  '/en/': typeof EnIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/en/models/$series': typeof EnModelsSeriesRouteWithChildren
  '/en/proposals/$slug': typeof EnProposalsSlugRoute
  '/models/$series/$model': typeof ModelsSeriesModelRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/models/': typeof EnModelsIndexRoute
  '/en/proposals/': typeof EnProposalsIndexRoute
  '/models/$series/': typeof ModelsSeriesIndexRoute
  '/admin/content/history': typeof AuthenticatedAdminContentHistoryRoute
  '/en/models/$series/$model': typeof EnModelsSeriesModelRoute
  '/en/models/$series/': typeof EnModelsSeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dealers': typeof DealersRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/terms': typeof TermsRoute
  '/en/about': typeof EnAboutRoute
  '/en/configurator': typeof EnConfiguratorRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/dealers': typeof EnDealersRoute
  '/en/offers': typeof EnOffersRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/stock': typeof EnStockRoute
  '/en/terms': typeof EnTermsRoute
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
  '/proposals/$slug': typeof ProposalsSlugRoute
  '/en': typeof EnIndexRoute
  '/models': typeof ModelsIndexRoute
  '/proposals': typeof ProposalsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/en/proposals/$slug': typeof EnProposalsSlugRoute
  '/models/$series/$model': typeof ModelsSeriesModelRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/en/models': typeof EnModelsIndexRoute
  '/en/proposals': typeof EnProposalsIndexRoute
  '/models/$series': typeof ModelsSeriesIndexRoute
  '/admin/content/history': typeof AuthenticatedAdminContentHistoryRoute
  '/en/models/$series/$model': typeof EnModelsSeriesModelRoute
  '/en/models/$series': typeof EnModelsSeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dealers': typeof DealersRoute
  '/en': typeof EnRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/terms': typeof TermsRoute
  '/en/about': typeof EnAboutRoute
  '/en/configurator': typeof EnConfiguratorRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/dealers': typeof EnDealersRoute
  '/en/models': typeof EnModelsRouteWithChildren
  '/en/offers': typeof EnOffersRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/proposals': typeof EnProposalsRouteWithChildren
  '/en/stock': typeof EnStockRoute
  '/en/terms': typeof EnTermsRoute
  '/models/$series': typeof ModelsSeriesRouteWithChildren
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
  '/proposals/$slug': typeof ProposalsSlugRoute
  '/en/': typeof EnIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/_authenticated/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/_authenticated/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/models': typeof AuthenticatedAdminModelsRoute
  '/_authenticated/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/en/models/$series': typeof EnModelsSeriesRouteWithChildren
  '/en/proposals/$slug': typeof EnProposalsSlugRoute
  '/models/$series/$model': typeof ModelsSeriesModelRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/models/': typeof EnModelsIndexRoute
  '/en/proposals/': typeof EnProposalsIndexRoute
  '/models/$series/': typeof ModelsSeriesIndexRoute
  '/_authenticated/admin/content/history': typeof AuthenticatedAdminContentHistoryRoute
  '/en/models/$series/$model': typeof EnModelsSeriesModelRoute
  '/en/models/$series/': typeof EnModelsSeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/cookies'
    | '/dealers'
    | '/en'
    | '/models'
    | '/offers'
    | '/privacy'
    | '/proposals'
    | '/sitemap.xml'
    | '/stock'
    | '/terms'
    | '/en/about'
    | '/en/configurator'
    | '/en/contact'
    | '/en/cookies'
    | '/en/dealers'
    | '/en/models'
    | '/en/offers'
    | '/en/privacy'
    | '/en/proposals'
    | '/en/stock'
    | '/en/terms'
    | '/models/$series'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
    | '/proposals/$slug'
    | '/en/'
    | '/models/'
    | '/proposals/'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/database'
    | '/admin/dealers'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/models'
    | '/admin/proposals'
    | '/admin/settings'
    | '/admin/system'
    | '/en/models/$series'
    | '/en/proposals/$slug'
    | '/models/$series/$model'
    | '/admin/'
    | '/en/models/'
    | '/en/proposals/'
    | '/models/$series/'
    | '/admin/content/history'
    | '/en/models/$series/$model'
    | '/en/models/$series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/cookies'
    | '/dealers'
    | '/offers'
    | '/privacy'
    | '/sitemap.xml'
    | '/stock'
    | '/terms'
    | '/en/about'
    | '/en/configurator'
    | '/en/contact'
    | '/en/cookies'
    | '/en/dealers'
    | '/en/offers'
    | '/en/privacy'
    | '/en/stock'
    | '/en/terms'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
    | '/proposals/$slug'
    | '/en'
    | '/models'
    | '/proposals'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/database'
    | '/admin/dealers'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/models'
    | '/admin/proposals'
    | '/admin/settings'
    | '/admin/system'
    | '/en/proposals/$slug'
    | '/models/$series/$model'
    | '/admin'
    | '/en/models'
    | '/en/proposals'
    | '/models/$series'
    | '/admin/content/history'
    | '/en/models/$series/$model'
    | '/en/models/$series'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/cookies'
    | '/dealers'
    | '/en'
    | '/models'
    | '/offers'
    | '/privacy'
    | '/proposals'
    | '/sitemap.xml'
    | '/stock'
    | '/terms'
    | '/en/about'
    | '/en/configurator'
    | '/en/contact'
    | '/en/cookies'
    | '/en/dealers'
    | '/en/models'
    | '/en/offers'
    | '/en/privacy'
    | '/en/proposals'
    | '/en/stock'
    | '/en/terms'
    | '/models/$series'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
    | '/proposals/$slug'
    | '/en/'
    | '/models/'
    | '/proposals/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/database'
    | '/_authenticated/admin/dealers'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/models'
    | '/_authenticated/admin/proposals'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/system'
    | '/en/models/$series'
    | '/en/proposals/$slug'
    | '/models/$series/$model'
    | '/_authenticated/admin/'
    | '/en/models/'
    | '/en/proposals/'
    | '/models/$series/'
    | '/_authenticated/admin/content/history'
    | '/en/models/$series/$model'
    | '/en/models/$series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ConfiguratorRoute: typeof ConfiguratorRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DealersRoute: typeof DealersRoute
  EnRoute: typeof EnRouteWithChildren
  ModelsRoute: typeof ModelsRouteWithChildren
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProposalsRoute: typeof ProposalsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockRoute: typeof StockRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/proposals/$slug': {
      id: '/proposals/$slug'
      path: '/$slug'
      fullPath: '/proposals/$slug'
      preLoaderRoute: typeof ProposalsSlugRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/models/r-950': {
      id: '/models/r-950'
      path: '/r-950'
      fullPath: '/models/r-950'
      preLoaderRoute: typeof ModelsR950RouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/r-680': {
      id: '/models/r-680'
      path: '/r-680'
      fullPath: '/models/r-680'
      preLoaderRoute: typeof ModelsR680RouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/r-520': {
      id: '/models/r-520'
      path: '/r-520'
      fullPath: '/models/r-520'
      preLoaderRoute: typeof ModelsR520RouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/$series': {
      id: '/models/$series'
      path: '/$series'
      fullPath: '/models/$series'
      preLoaderRoute: typeof ModelsSeriesRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/stock': {
      id: '/en/stock'
      path: '/stock'
      fullPath: '/en/stock'
      preLoaderRoute: typeof EnStockRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/proposals': {
      id: '/en/proposals'
      path: '/proposals'
      fullPath: '/en/proposals'
      preLoaderRoute: typeof EnProposalsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/offers': {
      id: '/en/offers'
      path: '/offers'
      fullPath: '/en/offers'
      preLoaderRoute: typeof EnOffersRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/models': {
      id: '/en/models'
      path: '/models'
      fullPath: '/en/models'
      preLoaderRoute: typeof EnModelsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/dealers': {
      id: '/en/dealers'
      path: '/dealers'
      fullPath: '/en/dealers'
      preLoaderRoute: typeof EnDealersRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cookies': {
      id: '/en/cookies'
      path: '/cookies'
      fullPath: '/en/cookies'
      preLoaderRoute: typeof EnCookiesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/configurator': {
      id: '/en/configurator'
      path: '/configurator'
      fullPath: '/en/configurator'
      preLoaderRoute: typeof EnConfiguratorRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/models/$series/': {
      id: '/models/$series/'
      path: '/'
      fullPath: '/models/$series/'
      preLoaderRoute: typeof ModelsSeriesIndexRouteImport
      parentRoute: typeof ModelsSeriesRoute
    }
    '/en/proposals/': {
      id: '/en/proposals/'
      path: '/'
      fullPath: '/en/proposals/'
      preLoaderRoute: typeof EnProposalsIndexRouteImport
      parentRoute: typeof EnProposalsRoute
    }
    '/en/models/': {
      id: '/en/models/'
      path: '/'
      fullPath: '/en/models/'
      preLoaderRoute: typeof EnModelsIndexRouteImport
      parentRoute: typeof EnModelsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/models/$series/$model': {
      id: '/models/$series/$model'
      path: '/$model'
      fullPath: '/models/$series/$model'
      preLoaderRoute: typeof ModelsSeriesModelRouteImport
      parentRoute: typeof ModelsSeriesRoute
    }
    '/en/proposals/$slug': {
      id: '/en/proposals/$slug'
      path: '/$slug'
      fullPath: '/en/proposals/$slug'
      preLoaderRoute: typeof EnProposalsSlugRouteImport
      parentRoute: typeof EnProposalsRoute
    }
    '/en/models/$series': {
      id: '/en/models/$series'
      path: '/$series'
      fullPath: '/en/models/$series'
      preLoaderRoute: typeof EnModelsSeriesRouteImport
      parentRoute: typeof EnModelsRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/proposals': {
      id: '/_authenticated/admin/proposals'
      path: '/admin/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AuthenticatedAdminProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/models': {
      id: '/_authenticated/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AuthenticatedAdminModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dealers': {
      id: '/_authenticated/admin/dealers'
      path: '/admin/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AuthenticatedAdminDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/database': {
      id: '/_authenticated/admin/database'
      path: '/admin/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AuthenticatedAdminDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/models/$series/': {
      id: '/en/models/$series/'
      path: '/'
      fullPath: '/en/models/$series/'
      preLoaderRoute: typeof EnModelsSeriesIndexRouteImport
      parentRoute: typeof EnModelsSeriesRoute
    }
    '/en/models/$series/$model': {
      id: '/en/models/$series/$model'
      path: '/$model'
      fullPath: '/en/models/$series/$model'
      preLoaderRoute: typeof EnModelsSeriesModelRouteImport
      parentRoute: typeof EnModelsSeriesRoute
    }
    '/_authenticated/admin/content/history': {
      id: '/_authenticated/admin/content/history'
      path: '/history'
      fullPath: '/admin/content/history'
      preLoaderRoute: typeof AuthenticatedAdminContentHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminContentRoute
    }
  }
}

interface AuthenticatedAdminContentRouteChildren {
  AuthenticatedAdminContentHistoryRoute: typeof AuthenticatedAdminContentHistoryRoute
}

const AuthenticatedAdminContentRouteChildren: AuthenticatedAdminContentRouteChildren =
  {
    AuthenticatedAdminContentHistoryRoute:
      AuthenticatedAdminContentHistoryRoute,
  }

const AuthenticatedAdminContentRouteWithChildren =
  AuthenticatedAdminContentRoute._addFileChildren(
    AuthenticatedAdminContentRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRouteWithChildren
  AuthenticatedAdminDatabaseRoute: typeof AuthenticatedAdminDatabaseRoute
  AuthenticatedAdminDealersRoute: typeof AuthenticatedAdminDealersRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminModelsRoute: typeof AuthenticatedAdminModelsRoute
  AuthenticatedAdminProposalsRoute: typeof AuthenticatedAdminProposalsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRouteWithChildren,
  AuthenticatedAdminDatabaseRoute: AuthenticatedAdminDatabaseRoute,
  AuthenticatedAdminDealersRoute: AuthenticatedAdminDealersRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminModelsRoute: AuthenticatedAdminModelsRoute,
  AuthenticatedAdminProposalsRoute: AuthenticatedAdminProposalsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnModelsSeriesRouteChildren {
  EnModelsSeriesModelRoute: typeof EnModelsSeriesModelRoute
  EnModelsSeriesIndexRoute: typeof EnModelsSeriesIndexRoute
}

const EnModelsSeriesRouteChildren: EnModelsSeriesRouteChildren = {
  EnModelsSeriesModelRoute: EnModelsSeriesModelRoute,
  EnModelsSeriesIndexRoute: EnModelsSeriesIndexRoute,
}

const EnModelsSeriesRouteWithChildren = EnModelsSeriesRoute._addFileChildren(
  EnModelsSeriesRouteChildren,
)

interface EnModelsRouteChildren {
  EnModelsSeriesRoute: typeof EnModelsSeriesRouteWithChildren
  EnModelsIndexRoute: typeof EnModelsIndexRoute
}

const EnModelsRouteChildren: EnModelsRouteChildren = {
  EnModelsSeriesRoute: EnModelsSeriesRouteWithChildren,
  EnModelsIndexRoute: EnModelsIndexRoute,
}

const EnModelsRouteWithChildren = EnModelsRoute._addFileChildren(
  EnModelsRouteChildren,
)

interface EnProposalsRouteChildren {
  EnProposalsSlugRoute: typeof EnProposalsSlugRoute
  EnProposalsIndexRoute: typeof EnProposalsIndexRoute
}

const EnProposalsRouteChildren: EnProposalsRouteChildren = {
  EnProposalsSlugRoute: EnProposalsSlugRoute,
  EnProposalsIndexRoute: EnProposalsIndexRoute,
}

const EnProposalsRouteWithChildren = EnProposalsRoute._addFileChildren(
  EnProposalsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnConfiguratorRoute: typeof EnConfiguratorRoute
  EnContactRoute: typeof EnContactRoute
  EnCookiesRoute: typeof EnCookiesRoute
  EnDealersRoute: typeof EnDealersRoute
  EnModelsRoute: typeof EnModelsRouteWithChildren
  EnOffersRoute: typeof EnOffersRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnProposalsRoute: typeof EnProposalsRouteWithChildren
  EnStockRoute: typeof EnStockRoute
  EnTermsRoute: typeof EnTermsRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnConfiguratorRoute: EnConfiguratorRoute,
  EnContactRoute: EnContactRoute,
  EnCookiesRoute: EnCookiesRoute,
  EnDealersRoute: EnDealersRoute,
  EnModelsRoute: EnModelsRouteWithChildren,
  EnOffersRoute: EnOffersRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnProposalsRoute: EnProposalsRouteWithChildren,
  EnStockRoute: EnStockRoute,
  EnTermsRoute: EnTermsRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ModelsSeriesRouteChildren {
  ModelsSeriesModelRoute: typeof ModelsSeriesModelRoute
  ModelsSeriesIndexRoute: typeof ModelsSeriesIndexRoute
}

const ModelsSeriesRouteChildren: ModelsSeriesRouteChildren = {
  ModelsSeriesModelRoute: ModelsSeriesModelRoute,
  ModelsSeriesIndexRoute: ModelsSeriesIndexRoute,
}

const ModelsSeriesRouteWithChildren = ModelsSeriesRoute._addFileChildren(
  ModelsSeriesRouteChildren,
)

interface ModelsRouteChildren {
  ModelsSeriesRoute: typeof ModelsSeriesRouteWithChildren
  ModelsR520Route: typeof ModelsR520Route
  ModelsR680Route: typeof ModelsR680Route
  ModelsR950Route: typeof ModelsR950Route
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsSeriesRoute: ModelsSeriesRouteWithChildren,
  ModelsR520Route: ModelsR520Route,
  ModelsR680Route: ModelsR680Route,
  ModelsR950Route: ModelsR950Route,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface ProposalsRouteChildren {
  ProposalsSlugRoute: typeof ProposalsSlugRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsSlugRoute: ProposalsSlugRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DealersRoute: DealersRoute,
  EnRoute: EnRouteWithChildren,
  ModelsRoute: ModelsRouteWithChildren,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  ProposalsRoute: ProposalsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockRoute: StockRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
