/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsR950RouteImport } from './routes/models.r-950'
import { Route as ModelsR680RouteImport } from './routes/models.r-680'
import { Route as ModelsR520RouteImport } from './routes/models.r-520'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsR950Route = ModelsR950RouteImport.update({
  id: '/models/r-950',
  path: '/models/r-950',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsR680Route = ModelsR680RouteImport.update({
  id: '/models/r-680',
  path: '/models/r-680',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsR520Route = ModelsR520RouteImport.update({
  id: '/models/r-520',
  path: '/models/r-520',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/models/r-520': typeof ModelsR520Route
  '/models/r-680': typeof ModelsR680Route
  '/models/r-950': typeof ModelsR950Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/models/r-520'
    | '/models/r-680'
    | '/models/r-950'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfiguratorRoute: typeof ConfiguratorRoute
  ContactRoute: typeof ContactRoute
  ModelsR520Route: typeof ModelsR520Route
  ModelsR680Route: typeof ModelsR680Route
  ModelsR950Route: typeof ModelsR950Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/r-950': {
      id: '/models/r-950'
      path: '/models/r-950'
      fullPath: '/models/r-950'
      preLoaderRoute: typeof ModelsR950RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/r-680': {
      id: '/models/r-680'
      path: '/models/r-680'
      fullPath: '/models/r-680'
      preLoaderRoute: typeof ModelsR680RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/r-520': {
      id: '/models/r-520'
      path: '/models/r-520'
      fullPath: '/models/r-520'
      preLoaderRoute: typeof ModelsR520RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  ModelsR520Route: ModelsR520Route,
  ModelsR680Route: ModelsR680Route,
  ModelsR950Route: ModelsR950Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
